tunnels:
  shard0:
    proto: tcp
    addr:  ac-szuisnz-shard-00-00.szhg7n5.mongodb.net:27017

  shard1:
    proto: tcp
    addr:  ac-szuisnz-shard-00-01.szhg7n5.mongodb.net:27017

  shard2:
    proto: tcp
    addr:  ac-szuisnz-shard-00-02.szhg7n5.mongodb.net:27017
