import "./globals.css";
import "./styles.css";
import Navbar from './components/navbar';
import Footer from './components/footer';

export const metadata = {
  title: "Niibish Aki",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn.iconscout.com/icon/free/png-256/free-teacup-tea-cup-without-handle-drink-beverage-food-emoj-symbol-30687.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
