import "./globals.css";
import "./styles.css";
import Navbar from './components/navbar';
import Footer from './components/footer';

export const metadata = {
  title: "Niibish Aki",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
